### ISSUE TITLE
cmd/occollector: TChannel used by jaeger-agent (default port: 14267) to send spans is not working

### ISSUE THREAD

**Issue by pjanotti** [census-instrumentation/opencensus-service#245] opened 2018-12-03 17:58 UTC
The endpoint used by the jaeger-agent to send to send spans in jaeger.thrift format is not working. The fix itself is trivial, just need to properly name the channel (change it to "jaeger-collector" and register a handler for the jaeger spans on the TChannel server - writing proper tests shouldn't be hard.

``` golang
		tch, terr := tchannel.NewChannel("jaeger-collector", new(tchannel.ChannelOptions)) // <- changed the name of the channel
		if terr != nil {
			err = fmt.Errorf("Failed to create NewTChannel: %v", terr)
			return
		}

		// Add the handler to the Jaeger batches.
		server := thrift.NewServer(tch)
		server.Register(jaeger.NewTChanCollectorServer(jr))
```

The jaeger-agent also can send Zipkin data via this channel. If we want that capability we should do it as a separate issue.

/cc @flands

**Comment by odeke-em** [comment] 2018-12-03 18:11
Thank you for filing and prescribing the fix for this @pjanotti!

I noticed this issue too early morning as I was writing https://github.com/census-instrumentation/opencensus-service/compare/jaeger-agent however wasn't sure of the root cause and was flooded with other stuff.

**Comment by odeke-em** [comment] 2018-12-03 20:41
Actually this seems like a regression that we should prioritize, I recall this working before.

**Comment by odeke-em** [comment] 2018-12-03 21:02
Nevermind, I went through the tests but didn't see our usage of the Thrift collector port 14267, we instead used 14268.

**Comment by yurishkuro** [comment] 2018-12-03 22:09
I am going to repeat my earlier warning - we're planning to deprecate and remove TChannel soon. `jaeger-collector` now has a gRPC endpoint.

**Comment by odeke-em** [comment] 2018-12-03 22:48
>I am going to repeat my earlier warning - we're planning to deprecate and remove TChannel soon. jaeger-collector now has a gRPC endpoint.

@yurishkuro gotcha and thank you! We are aiming to have as much compatibility as possible since people deploying these systems might be using even the earliest versions of Jaeger so we can basically support all versions for maximum compatibility for the interceptors/receivers.

**Closed** 2018-12-05 06:02 UTC
Labels: bug
