### ISSUE TITLE
make agent fails

### ISSUE THREAD

**Issue by sagar1009** [census-instrumentation/opencensus-service#504] opened 2019-03-26 22:25 UTC
While running make agent command, I'm getting an error as 

 m-c02ww12xhtdg:opencensus-service User$ make docker-agent
COMPONENT=agent /Applications/Xcode.app/Contents/Developer/usr/bin/make docker-component
GOOS=linux /Applications/Xcode.app/Contents/Developer/usr/bin/make agent
GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/ocagent_linux -ldflags "-X github.com/census-instrumentation/opencensus-service/internal/version.GitHash=405c9e3 " ./cmd/ocagent
../../../go/pkg/mod/github.com/spf13/viper@v1.2.1/viper.go:35:2: 
../../../go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:1:1: expected 'package', found 'EOF'
make[2]: *** [agent] Error 1
make[1]: *** [docker-component] Error 2
make: *** [docker-agent] Error 2
---------------------------------------------------------------------------------------
m-c02ww12xhtdg:opencensus-service User$ make agent 
GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/ocagent_darwin -ldflags "-X github.com/census-instrumentation/opencensus-service/internal/version.GitHash=405c9e3 " ./cmd/ocagent
../../../go/pkg/mod/github.com/spf13/viper@v1.2.1/viper.go:35:2: 
../../../go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/encode.go:1:1: expected 'package', found 'EOF'
make: *** [agent] Error 1

System configuration is below : 

- go version go1.12.1 darwin/amd64
-  i386-apple-darwin11.3.0
- Bazaar 2.7.0

**Comment by flands** [comment] 2019-03-27 00:09
We will look into it, but in the meantime, use the latest release: https://github.com/census-instrumentation/opencensus-service/releases/tag/0.1.4

**Comment by songy23** [comment] 2019-03-27 00:17
I couldn't reproduce the error on my Linux workstation:
```bash
$ make docker-agent
COMPONENT=agent make docker-component
make[1]: Entering directory '~/go/src/github.com/census-instrumentation/opencensus-service'
GOOS=linux make agent
make[2]: Entering directory '~/go/src/github.com/census-instrumentation/opencensus-service'
GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/ocagent_linux -ldflags "-X github.com/census-instrumentation/opencensus-service/internal/version.GitHash=405c9e3 " ./cmd/ocagent
make[2]: Leaving directory '~/go/src/github.com/census-instrumentation/opencensus-service'
cp ./bin/ocagent_linux ./cmd/ocagent/
docker build -t ocagent ./cmd/ocagent/
Sending build context to Docker daemon  78.56MB
Step 1/8 : FROM alpine:3.7 as helper
 ---> 34ea7509dcad
Step 2/8 : RUN apk update     && apk add --no-cache ca-certificates     && update-ca-certificates     && touch ./config.yaml
 ---> Using cache
 ---> fbed73265520
Step 3/8 : FROM scratch
 ---> 
Step 4/8 : COPY ocagent_linux /
 ---> 718a22d2f3da
Step 5/8 : COPY --from=helper ./config.yaml config.yaml
 ---> a6896f9b56a7
Step 6/8 : COPY --from=helper /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
 ---> 9db8596a410e
Step 7/8 : ENTRYPOINT ["/ocagent_linux"]
 ---> Running in ba70c9995d9f
Removing intermediate container ba70c9995d9f
 ---> fb61fa1b4609
Step 8/8 : EXPOSE 55678 55679
 ---> Running in 59fed9bd3753
Removing intermediate container 59fed9bd3753
 ---> ba558997e58e
Successfully built ba558997e58e
Successfully tagged ocagent:latest
rm ./cmd/ocagent/ocagent_linux
make[1]: Leaving directory '~/go/src/github.com/census-instrumentation/opencensus-service'
```

**Comment by sagar1009** [comment] 2019-03-27 00:19
I’m running this set up on my Mac laptop.

**Comment by sagar1009** [comment] 2019-03-27 00:36
Is there constraints using this over mac?

**Comment by pjanotti** [comment] 2019-03-27 01:21
I use this on mac but my go is 1.11.4 - can you `go clean --modcache` and retry? Not sure if it is really this case but this SO answer implies problems with the install https://stackoverflow.com/a/31112032

**Comment by flands** [comment] 2019-04-24 22:17
@sagar1009 are you still having issues with this?

**Comment by pjanotti** [comment] 2019-06-12 19:21
Closing for lack of new information on this.

**Closed by pjanotti** 2019-06-12 19:21 UTC
