### ISSUE TITLE
receiver/jaeger: translation of Jaeger agent tags are lost

### ISSUE THREAD

**Issue by flands** [census-instrumentation/opencensus-service#605] opened 2019-07-12 16:35 UTC
Configure an application to send Jaeger to the Jaeger agent. Configure the Jaeger agent to add tags to the data it is sending out. Configure the Jaeger agent to send tchannel to the OC collector. Have the OC collector export in OC to a backend.

Expected: Jaeger agent tags are seen on spans

Actual: Jaeger agent tags are NOT seen on spans.

**Comment by pjanotti** [comment] 2019-07-15 20:42
@flands per https://github.com/jaegertracing/jaeger/issues/833#issuecomment-474512380 Jaeger agent is only capable to add tags to gRPC. It seems the case that you described.

**Comment by pjanotti** [comment] 2019-08-09 04:06
Can you try the same against OpenTelemetry service that has a Jaeger gRPC receiver?

**Comment by pankajmt** [comment] 2019-08-15 02:00
I opened https://github.com/census-instrumentation/opencensus-java/issues/1959 but was closed as a duplicate of this one. 

But I am not completely sure what the recommendation is. 

Reference to OpenCensus Service deployment architecture: https://github.com/census-instrumentation/opencensus-service#user-content-deploy

I have jaeger traces -> OpenCensus Agent -> OpenCensus Collector -> Stackdriver and looks like the (application) tags and metadata gets dropped or at least I do not see them in Stackdriver console.

Would the Stackdriver exporter export tags and metadata from jaeger traces? Or are they getting dropped even before Stackdriver exporter?

**Comment by pankajmt** [comment] 2019-08-15 02:21
is the recommendation to use thrift receiver instead of http for ocagent or occollector both? right now i have 

ocagent:

        receivers:
            jaeger:
                collector_http_port: {{ .Values.jaeger_thrift_http_port }}

occollector:

        receivers:
            jaeger:
                jaeger-thrift-http-port: {{ .Values.jaeger_thrift_http_port }}

**Comment by dashpole** [comment] 2022-11-07 15:33
This repository is now archived, and is succeeded by https://github.com/open-telemetry/opentelemetry-collector.

**Closed by dashpole** 2022-11-07 15:33 UTC
