### ISSUE TITLE
interceptor/opencensus: return error immediately if the first message does not have a node

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#53] opened 2018-10-02 20:01 UTC
Currently I am doing a retry waiting for the first node to be sent, 15 times. However, we should fail fast
https://github.com/census-instrumentation/opencensus-service/blob/e939042488a2fe395203c32612a90f208e2476a7/interceptor/opencensus/opencensus.go#L59-L78

Corrected offline by @bogdandrutu

**Comment by bogdandrutu** [comment] 2018-10-02 20:07
This is a duplicate of https://github.com/census-instrumentation/opencensus-service/issues/52

**Comment by odeke-em** [comment] 2018-10-02 20:08
We hit "New Issue" at the same time as I was typing and chatting offline :)

**Closed** 2018-10-03 00:15 UTC
Labels: P0
